### ISSUE TITLE
use title in github repo as book title ? 

### ISSUE THREAD

**Issue by cderv** [gvwilson/tidynomicon#30]
Hi, 

Great book ! 

Just a thought: I find the the title a the Github Repo is a great title
> The tidynomicon: A Brief Introduction to R for Python Programmers 

It does not appear like this in the book itself
![image](https://user-images.githubusercontent.com/6791940/57126453-4a8bc100-6d8d-11e9-995e-24c8880ddf58.png)

I would find it an improvement to have both part of the title in this first page. 

It is possible to ass as a subtitle here normally 
https://github.com/gvwilson/tidynomicon/blob/0080acb2a993bf979f0f8e27ae2acb35cbcd2fdb/index.Rmd#L2-L4
```yaml
title: "The Tidynomicon"
subtitle: "A Brief Introduction to R for Python Programmers"
author: "Greg Wilson"
```
or in the title with a second part using `:`

A I began, just a thought.
